### ISSUE TITLE
Umgebungsvariablen statt token.txt

### ISSUE THREAD

**Issue by Silas217209** [torbiboi/fiiliiuus#3]
Spricht irgendetwas gegen die Verwendung von Umgebungsvariablen? Ansonsten wären diese für diesen Zweck gut geeinget.

**Comment by torbiboi** [comment]
Du hast absolut Recht, da spricht ganz und gar nichts gegen. Das ist eine viel elegantere Lösung und verhindert außerdem, dass jemand versehentlich einen Token commitet.
